### ISSUE TITLE
Function to toggle automatic cursorcross

### ISSUE THREAD

**Issue by DerWeh** [mtth/cursorcross.vim#9]
Could you add a function to toggle this plug-in? Sometime I enter buffers with very long data that will be wrapped. A cursor line significantly slows done vim in that case. As long as the plug-in runs I cannot simply disable the cursor line, as `cursorcross` will enable it again as soon as I leave insertmode.

**Comment by mtth** [comment]
Would a global toggle be sufficient for your use-case?

**Comment by DerWeh** [comment]
Yes, that should suffice.

**Comment by mtth** [comment]
3792dc063354e457a0d50fd2230e321c35d8c705 adds a `CursorcrossToggle` command which lets you toggle dynamic behavior on/off! Feel free to reopen if you run into any issues.
